### ISSUE TITLE
Update Gutenberg block editor to Latest version

### ISSUE THREAD

**Issue by bawarkamalqader** [mauricewijnia/block-editor#1]
is it possible to bump version of gutenberg to latest version?

i think the new version is 12, and maybe more stable

I was wondering what are the issues that would arise if we try to do so

**Comment by mauricewijnia** [comment]
Hi, I'll definitly do that, but right now i'm focussed on making everything work like it should.

Updating to a different Gutenberg version usually takes some time and is a bit of a hassle because the Gutenberg team does not always version their packages correctly.
